# Generated by Django 4.2.3 on 2023-08-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.CharField(default='', editable=False, max_length=250),
        ),
    ]
